INSERT INTO order__item(cost, weight, orderId, itemId) VALUE(180, 18, 1, 1);
INSERT INTO order__item(cost, weight, orderId, itemId) VALUE(253, 23, 2, 1);
INSERT INTO order__item(cost, weight, orderId, itemId) VALUE(208, 13, 5, 1);
INSERT INTO order__item(cost, weight, orderId, itemId) VALUE(220, 22, 1, 2);
INSERT INTO order__item(cost, weight, orderId, itemId) VALUE(405, 27, 9, 2);
INSERT INTO order__item(cost, weight, orderId, itemId) VALUE(360, 20, 6, 2);
INSERT INTO order__item(cost, weight, orderId, itemId) VALUE(150, 15, 1, 3);
INSERT INTO order__item(cost, weight, orderId, itemId) VALUE(320, 20, 3, 3);
INSERT INTO order__item(cost, weight, orderId, itemId) VALUE(300, 20, 9, 3);
