INSERT INTO tag(title) VALUE("spicy");
INSERT INTO tag(title) VALUE("salty");
INSERT INTO tag(title) VALUE("peppery");
INSERT INTO tag(title) VALUE("red");
INSERT INTO tag(title) VALUE("umami");
INSERT INTO tag(title) VALUE("sweet");
INSERT INTO tag(title) VALUE("brown");
INSERT INTO tag(title) VALUE("italian");
INSERT INTO tag(title) VALUE("fresh");
