INSERT INTO Users(firstname, lastname, permission, credit_card_number, address, email, password) VALUE("Rhonda", "Ferguson", 0, 123456789101112, "0", "RFerguson@gmail.com", bicynidbmr);
INSERT INTO Users(firstname, lastname, permission, credit_card_number, address, email, password) VALUE("Karen", "Cross", 0, 123456789101112, "1", "KCross@gmail.com", rkkbfekrkw);
INSERT INTO Users(firstname, lastname, permission, credit_card_number, address, email, password) VALUE("Dawn", "Wall", 0, 123456789101112, "2", "DWall@gmail.com", hfanyctmca);
INSERT INTO Users(firstname, lastname, permission, credit_card_number, address, email, password) VALUE("Katelyn", "Foster", 0, 123456789101112, "3", "KFoster@gmail.com", kxodbcveez);
INSERT INTO Users(firstname, lastname, permission, credit_card_number, address, email, password) VALUE("Jonathan", "Martinez", 0, 123456789101112, "4", "JMartinez@gmail.com", ajnspipbyj);
INSERT INTO Users(firstname, lastname, permission, credit_card_number, address, email, password) VALUE("Stephanie", "Gibbs", 1, 123456789101112, "5", "SGibbs@gmail.com", kqzpgtuqsz);
INSERT INTO Users(firstname, lastname, permission, credit_card_number, address, email, password) VALUE("Kathleen", "Dominguez", 1, 123456789101112, "6", "KDominguez@gmail.com", kamyuqnvru);
INSERT INTO Users(firstname, lastname, permission, credit_card_number, address, email, password) VALUE("Anthony", "Hensley", 1, 123456789101112, "7", "AHensley@gmail.com", zvtpqvnlqb);
INSERT INTO Users(firstname, lastname, permission, credit_card_number, address, email, password) VALUE("Michael", "Fisher", 2, 123456789101112, "8", "MFisher@gmail.com", yufxcpvifk);
