INSERT INTO item__tags_tag(itemId, tagId) VALUES(8, 8);
INSERT INTO item__tags_tag(itemId, tagId) VALUES(7, 7);
INSERT INTO item__tags_tag(itemId, tagId) VALUES(1, 9);
INSERT INTO item__tags_tag(itemId, tagId) VALUES(2, 6);
INSERT INTO item__tags_tag(itemId, tagId) VALUES(8, 2);
INSERT INTO item__tags_tag(itemId, tagId) VALUES(2, 8);
INSERT INTO item__tags_tag(itemId, tagId) VALUES(8, 1);
INSERT INTO item__tags_tag(itemId, tagId) VALUES(5, 3);
INSERT INTO item__tags_tag(itemId, tagId) VALUES(3, 4);
