INSERT INTO order_(total_cost, total_weight, order_status, userId, staffId) VALUE(641, 54, 1, 2, 6);
INSERT INTO order_(total_cost, total_weight, order_status, userId, staffId) VALUE(641, 54, 1, 2, 6);
INSERT INTO order_(total_cost, total_weight, order_status, userId, staffId) VALUE(641, 54, 1, 2, 6);
INSERT INTO order_(total_cost, total_weight, order_status, userId, staffId) VALUE(985, 69, 0, 4, 6);
INSERT INTO order_(total_cost, total_weight, order_status, userId, staffId) VALUE(985, 69, 0, 4, 6);
INSERT INTO order_(total_cost, total_weight, order_status, userId, staffId) VALUE(985, 69, 0, 4, 6);
INSERT INTO order_(total_cost, total_weight, order_status, userId, staffId) VALUE(770, 55, 0, 4, 6);
INSERT INTO order_(total_cost, total_weight, order_status, userId, staffId) VALUE(770, 55, 0, 4, 6);
INSERT INTO order_(total_cost, total_weight, order_status, userId, staffId) VALUE(770, 55, 0, 4, 6);
