INSERT INTO OrderItem(cost, weight, item_id) VALUE(180, 18, 1);
INSERT INTO OrderItem(cost, weight, item_id) VALUE(368, 23, 2);
INSERT INTO OrderItem(cost, weight, item_id) VALUE(130, 13, 5);
INSERT INTO OrderItem(cost, weight, item_id) VALUE(220, 22, 1);
INSERT INTO OrderItem(cost, weight, item_id) VALUE(513, 27, 9);
INSERT INTO OrderItem(cost, weight, item_id) VALUE(300, 20, 6);
INSERT INTO OrderItem(cost, weight, item_id) VALUE(150, 15, 1);
INSERT INTO OrderItem(cost, weight, item_id) VALUE(200, 20, 3);
INSERT INTO OrderItem(cost, weight, item_id) VALUE(380, 20, 9);
